venue_name: "NIT Trichy Demo Arena"

frame_width: 1920
frame_height: 1080

total_capacity: 5000

zones:

  - id: "A"
    name: "ENTRY"
    max_capacity: 500
    polygon:
      [[0,0],[640,0],[640,540],[0,540]]
    exits:
      ["Gate 1","Gate 2"]

  - id: "B"
    name: "STAGE"
    max_capacity: 1800
    polygon:
      [[640,0],[1280,0],[1280,540],[640,540]]
    exits:
      ["Stage Exit Left","Stage Exit Right"]

  - id: "C"
    name: "VIP"
    max_capacity: 700
    polygon:
      [[1280,0],[1920,0],[1920,540],[1280,540]]
    exits:
      ["VIP Exit"]

  - id: "D"
    name: "ENTRY SOUTH"
    max_capacity: 600
    polygon:
      [[0,540],[640,540],[640,1080],[0,1080]]
    exits:
      ["Gate 3"]

  - id: "E"
    name: "MAIN CROWD"
    max_capacity: 1500
    polygon:
      [[640,540],[1280,540],[1280,1080],[640,1080]]
    exits:
      ["Emergency Exit"]

  - id: "F"
    name: "EXIT"
    max_capacity: 700
    polygon:
      [[1280,540],[1920,540],[1920,1080],[1280,1080]]
    exits:
      ["Main Exit"]

gates:

  - name: "Gate 1"
    location: [120,70]
    type: "entry"

  - name: "Gate 2"
    location: [520,70]
    type: "entry"

  - name: "Gate 3"
    location: [120,980]
    type: "entry"

  - name: "VIP Exit"
    location: [1810,220]
    type: "exit"

  - name: "Main Exit"
    location: [1810,900]
    type: "exit"

  - name: "Emergency Exit"
    location: [960,1070]
    type: "emergency"
